### ISSUE TITLE
Update Build for 16.1

### ISSUE THREAD

**Issue by RascoApps** [jnm2/DevExpressMods#6]
I just came across this after finding your post on a support site. Could I just do a binding redirect to point to 16.1 or do we update the entire project?

**Comment by jnm2** [comment]
After a major (or even minor) version upgrade there is always the possibility of internals changing, so I'd prefer to update the project and verify that nothing has changed. There was a breaking change in the public XtraReports API between 15.1 and 15.2, for example. But it may well work.

I'll update the project to 16.1 and confirm everything sometime today or tomorrow.

**Comment by RascoApps** [comment]
Ok, great. Looking forward to it. Our Report Designer is VERY excited.

Will this feature allow conditional formatting to work on these summary fields at appropriate group levels?

Then do you have any experience creating custom datasources?

We are looking to add support for SQL Analysis Services (Tabular and Excel’s PowerPivot) via ADO that I already have working to return a dataset by setting the data source in the Report’s script.

There are some remaining issues I would like to handle and add the data source to the report toolbar like the XAF data sources.

**Comment by jnm2** [comment]
[Here you are.](https://github.com/jnm2/DevExpressMods/releases/tag/v1.0.0) I didn't find any issues. I did come to the realization that I need to add more test coverage, but for the time being I think we're good.

I'm going to go ahead and [publish this to NuGet](https://www.nuget.org/packages/DevExpressMods/1.0.0) because I think that will make it easier to use and stay updated, but you are welcome to use the project directly of course if you want to.

> Will this feature allow conditional formatting to work on these summary fields at appropriate group levels?

Yes. Anywhere you can use a `CalculatedField`, you can use a `SummaryField`.

> Then do you have any experience creating custom datasources?
> 
> We are looking to add support for SQL Analysis Services (Tabular and Excel’s PowerPivot) via ADO that I already have working to return a dataset by setting the data source in the Report’s script. 
> 
> There are some remaining issues I would like to handle and add the data source to the report toolbar like the XAF data sources.

I have quite a bit of experience. Custom datasources are already supported by XtraReports. It uses the `TypeDescriptor` system to bind data. (That allows you to use `DataSet`, or direct object binding, or your own classes tailoring the `TypeDescriptor` interfaces. I do the latter because I lazy-load all data.) I am not however familiar with XAF. This seems like more of a general XtraReports question to me which the DevExpress team would be able to answer.

Can you use [use gitter](https://gitter.im/jnm2/DevExpressMods) for questions that aren't specific to a certain issue? I'd like to continue the conversation there. Thanks!
